Pract.05: Add 01-08 | Mihail Dimitrov
SirLex/UP pull request #12
Opened 2024-11-07 18:52 UTC by MihailDimitrov1235

Mihail Dimitrov
3 3MI0600472

2024-11-07 19:10 UTC, SirLex reviewed
Overall I am very happy with the tasks! Good job.
Few notes will be to aim to write code such that others can understand easily!
Minor comments, but still great!

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task01.cpp
> +void average(int arr[], int n) {
We accept arr as a logical name for a variable, I can not say the same thing for n -> try to use meaningful namings for your variables, sizeOfArray? countOfElements?

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task01.cpp
> +	cout << closest;
We should strive to have a single responsibility functions -> have a separate function for finding closest, and a separate for average. One function should have only 1 responsibility.

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task01.cpp
> +	int arr[1000];
We should use constants and not magical numbers such as 1000.

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task01.cpp
> +void average(int arr[], int n) {
Also, why not return the average? We should strive further from void functions. When we have some return type we know what to expect from a function plus it is easier to test as you will see in the following years

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task02.cpp
> +	}
good catch! I like it

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task05.cpp
> +	int j = 0;
not used variable.

2024-11-07 19:10 UTC, SirLex commented on Sem.05/Pract.05/MihailDimitrov/Task08.cpp
> +        int el = arr[i];
el ? as element? write it out it is easier to read and understand the code that way.

2024-11-11 20:20 UTC, AtanasHrist0v requested changes
Please review the instructions [here](https://github.com/SirLex/UP/blob/main/Git%20&%20GitHub%20Tutorials/README.md), point 5, last bullet point.

2024-11-12 22:18 UTC, merged