Pract.04: Upload tasks with changed file names
SirLex/UP pull request #33
Opened 2024-11-11 19:01 UTC by VelinaSouroujon

Velina Souroujon
3 6MI0600415

2024-11-11 19:59 UTC, AtanasHrist0v requested changes
Please review the instructions [here](https://github.com/SirLex/UP/blob/main/Git%20&%20GitHub%20Tutorials/README.md), point 5, last bullet point.

2024-11-17 17:36 UTC, SirLex commented
Please add your files to personalized folder

2024-11-19 09:52 UTC, AtanasHrist0v requested changes
Please sync this branch or manually add the original Sem.04/Pract.04/README.md. After that I'll be able to merge.

2024-11-19 21:34 UTC, AtanasHrist0v approved these changes

2024-11-19 21:35 UTC, merged